[phases.setup]
nixPkgs = ["dotnetCorePackages.sdk_9_0"]

[phases.build]
cmds = ["dotnet publish src/FleetControl.WebAPI/FleetControl.WebAPI.csproj -c Release -o out"]

[start]
cmd = "dotnet out/FleetControl.WebAPI.dll"
